export function collectionStyles(width: number, height: number, dark: boolean) {
  const portrait = height > width;
  const wide = width > height;
  return `
*{box-sizing:border-box}html,body{margin:0;width:${width}px;height:${height}px;overflow:hidden;font-family:Body,sans-serif;background:${dark ? '#101016' : '#f4f1eb'};color:${dark ? '#faf8f4' : '#191820'}}
#socialpro-motion{position:relative;width:100%;height:100%;overflow:hidden;--card:${dark ? '#22222c' : '#fff'};--line:${dark ? '#ffffff29' : '#19182024'};--accent:${dark ? '#ffab85' : '#a32e5b'}}
.rail{position:absolute;top:7%;left:8.5%;right:8.5%;display:flex;align-items:center;justify-content:space-between;gap:20px;z-index:2}.rail img{width:148px;height:78px;object-fit:contain;background:#faf8f4;padding:9px 12px;border-radius:12px}.rail span{font-size:12px;font-weight:700;letter-spacing:2px}
.content{--fit:1;position:absolute;left:8.5%;right:8.5%;top:${portrait ? '27%' : '26%'};height:${portrait ? '52%' : '57%'};display:flex;flex-direction:column;justify-content:center;gap:calc(24px * var(--fit));z-index:1}.content>*{flex-shrink:0;min-width:0}
.eyebrow{font-size:12px;letter-spacing:2px;font-weight:700;color:var(--accent)}h1{font-family:Display,sans-serif;font-size:calc(${portrait ? 92 : 76}px * var(--fit));font-weight:800;text-transform:uppercase;line-height:.98;letter-spacing:-.8px;margin:0;overflow-wrap:anywhere;max-width:100%}
.description,.contact,.item span{font-size:max(20px,calc(28px * var(--fit)));line-height:1.4;overflow-wrap:anywhere;white-space:pre-wrap}.description{max-width:900px}
.item{display:flex;align-items:center;gap:calc(22px * var(--fit));padding:calc(18px * var(--fit)) 22px;min-width:0}.marker{font-family:Display;font-size:32px;color:var(--accent);flex-shrink:0;line-height:1}.item span{min-width:0}.steps,.checklist,.quiz,.timeline{display:grid;gap:calc(12px * var(--fit))}
.steps .item{background:var(--card);border:1px solid var(--line);border-radius:16px;box-shadow:5px 5px 0 var(--line);transform-origin:bottom left}.steps .item:nth-child(2){margin-left:18px}.steps .item:nth-child(3){margin-left:36px}
.contact{background:#faf8f4;color:#16161d;border-radius:100px;padding:calc(26px * var(--fit)) 30px;display:flex;align-items:center;justify-content:space-between;gap:20px;border:2px solid #e03070}.contact span{min-width:0}.contact b{font-size:46px;color:#a32e5b;line-height:1}
.compare{display:grid;grid-template-columns:1fr 1fr;gap:18px}.compare .item{align-items:flex-start;flex-direction:column;justify-content:space-between;min-height:calc(188px * var(--fit));border:1px solid var(--line);border-radius:14px;background:var(--card)}.compare .item:last-child{background:#f7e7df;color:#191820;border-color:#f5632a}.compare .item:last-child .marker{color:#a32e5b}
.checklist .item{border-bottom:1px solid var(--line);padding-left:0}.checklist .marker{width:38px;height:38px;border-radius:50%;background:var(--card);border:1px solid var(--line);padding:3px}.checklist svg{width:30px;height:30px}.checklist path{fill:none;stroke:#e03070;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:42}
.quiz .item{border-radius:100px;background:var(--card);border:1px solid var(--line)}.quiz .marker{border-right:1px solid var(--line);padding-right:20px}
.live{border:1px solid var(--line);border-radius:20px;background:var(--card);padding:18px 12px}.live .item{padding:calc(10px * var(--fit)) 18px}.waves{display:flex;align-items:center;gap:7px;height:36px;margin:0 18px 12px}.waves i{height:30px;width:6px;background:#e03070;border-radius:6px}
.timeline{position:relative;gap:18px}.timeline .item{padding:6px 0;position:relative}.timeline .marker{border:1px solid var(--line);background:var(--card);width:48px;height:48px;display:grid;place-items:center;border-radius:50%;font-size:23px}.connector{position:absolute;left:23px;top:20px;bottom:20px;width:3px;background:linear-gradient(#f5632a,#e03070,#8b3aad);transform-origin:top}
.art{position:absolute;inset:0;pointer-events:none;opacity:.8}.art i{position:absolute;display:block}.design-statement .art i{width:140%;height:12px;bottom:15%;left:-20%;transform:rotate(-15deg);background:#e03070}.design-statement .art i:nth-child(2){bottom:18%;background:#8b3aad}.design-statement .art i:nth-child(3){bottom:21%;background:#f5632a}
.design-metric .art i:first-child{width:${wide ? 540 : 640}px;height:${wide ? 540 : 640}px;border-radius:50%;border:36px solid ${dark ? '#e0307020' : '#e0307015'};top:19%;left:${wide ? '42%' : '24%'}}.design-metric h1{font-size:calc(${portrait ? 112 : 92}px * var(--fit));color:var(--accent)}
.design-quote .content{border-left:5px solid #e03070;padding-left:28px}.design-quote .art:before{content:'“';font-family:Display;font-size:360px;line-height:1;position:absolute;top:10%;right:8%;color:${dark ? '#e0307025' : '#e030701c'}}.design-quote .description{font-size:max(20px,calc(24px * var(--fit)))}
.design-contact .art i:first-child{width:280px;height:280px;border:2px solid var(--line);border-radius:50%;right:-100px;top:17%}.design-live .art i:first-child{width:90%;height:180px;bottom:2%;left:25%;background:linear-gradient(120deg,#f5632a18,#e030701c);transform:rotate(-18deg)}
.rule{position:absolute;bottom:13%;left:8.5%;right:8.5%;height:1px;background:currentColor;opacity:.15}footer{position:absolute;left:8.5%;right:8.5%;bottom:9%;display:flex;justify-content:space-between;font-size:12px;font-weight:700;letter-spacing:1.5px}footer span{opacity:.55;font-size:10px}
`;
}
