import { createHash } from 'node:crypto';
import { sendResendEmail } from '@/lib/email/sendResendEmail';
import { SITE_URL } from '@/lib/site-url';

/** URL is generated by Better Auth, never supplied by a Studio form. */
export async function sendStudioVerificationEmail(
  email: string,
  url: string,
  token: string,
) {
  const target = new URL(url);
  if (
    target.origin !== new URL(SITE_URL).origin ||
    target.pathname !== '/api/auth/verify-email'
  )
    throw new Error('Invalid verification destination');
  const link = target.href.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
  await sendResendEmail(
    'studioEmailVerification',
    {
      from: 'SocialPro <noreply@socialpro.es>',
      replyTo: 'marketing@socialpro.es',
      to: email,
      subject: 'Verifica tu correo para SocialPro Studio',
      text: `Confirma tu correo para activar tu invitación a SocialPro Studio. Este enlace caduca en 1 hora:\n${target.href}\nDespués, vuelve a abrir tu invitación. Si no has solicitado este acceso, ignora el correo.`,
      html: `<!doctype html><html lang="es" dir="ltr"><head><title>Verifica tu correo para SocialPro Studio</title></head><body><div lang="es" dir="ltr" style="max-width:520px;margin:auto;padding:24px;font:16px/1.6 Arial,sans-serif;color:#202026;background:#fff"><h1 style="font-size:24px">Confirma tu correo</h1><p>Un paso antes de activar tu espacio en SocialPro Studio. El enlace caduca en 1 hora.</p><p><a href="${link}" style="display:inline-block;padding:14px 24px;color:#fff;background:#a32156;text-decoration:none;border-radius:8px">Verificar mi correo</a></p><p>Después, vuelve a abrir tu invitación de SocialPro.</p><p>Si no has solicitado este acceso, puedes ignorar este mensaje.</p></div></body></html>`,
    },
    {
      idempotencyKey: `studio-verify-${createHash('sha256').update(token).digest('hex')}`,
    },
  );
}
